remote_theme: pages-themes/cayman@v0.2.0

title: 'AWS Cloud Practitioner Study Notes (CLF-C02)'
description: 'If you are preparing for AWS Cloud Practitioner Exam (CLF-C02), this guide will help you with quick revision before the exam. I share the notes I used to study and pass exam.'
show_downloads: false

github:
  repository_url: '/'
  owner_url: "https://portfolio.kananinirav.com/"
  all_certification: 'https://certification.kananinirav.com/'

# Set which comment system to use
comments:
  # 'disqus' / 'giscus' / 'utterances' are available
  provider: giscus

# You must install giscus github app before use.(https://github.com/apps/giscus)
# Make sure all variables are set properly. Check below link for detail.
# https://giscus.vercel.app/
giscus:
  repo:                "kananinirav/AWS-Certified-Cloud-Practitioner-Notes"
  repo-id:             "R_kgDOHx8vjA"
  category:            "Comments"
  category-id:         "DIC_kwDOHx8vjM4CS2vu"
  mapping:             "pathname"
  data-strict:         "1"
  reaction-enabled:    "1"
  theme:               "light"
  crossorigin:         "anonymous"
  input-position:      "top"
  loading:             "lazy"

defaults:
  - scope:
      path: ""
    values:
      image: /images/AWS-Cloud-Practitioner.png
  - scope:
      path: "/sections/*.md"
    values:
      link: true
